package de.take_weiland.CameraCraft.Common.Network;

public enum NetAction
{
  UNKNOWN, 
  REQUEST_PHOTO, 
  SERVER_REQUEST_PHOTO, 
  PHOTO_TAKEN, 

  PHOTO_TAKEN_NON_PLAYER, 
  REQUEST_IMAGEDATA, 
  IMAGEDATA, 

  REQUEST_VIEW_PHOTOS, 

  REQUEST_RENAME, 

  REQUEST_PRINT, 
  REQUEST_TELEPORT, 
  REQUEST_DELETE, 

  SCREENSHOT_CAMERA_ENTITY, 

  FILEPART, 

  CONFIRM_CAMERACRAFT;
}